### ISSUE TITLE
Remaining filter lifetime is displayed in hours; should be days

### ISSUE THREAD

**Issue by XilviuX** [Tvalley71/dantherm#40]
The integration shows the lifetime left in hours, which is not readable. Tried to set the unit to days; it only works in the graph view when I look at the properties of the entity, but not in the dashboard which still displays hours

<img width="316" alt="Capture d’écran 2024-06-02 à 16 29 55" src="https://github.com/Tvalley71/dantherm/assets/163339991/bdcdd6e1-ba4e-45e5-9e7a-045402a758d9">

**Comment by Tvalley71** [comment]
If you click on the sensor, a pop-up will show with a graph. Click on the gear symbol in the upper right corner. There should be something like "display precision". Choose the value without any decimals. 

I cannot find a way to make this the default from the integration.

Best regards
Tvalley71

**Comment by XilviuX** [comment]
This works, thanks!
