### ISSUE TITLE
Missing temperatures

### ISSUE THREAD

**Issue by Debug1Bug** [Tvalley71/dantherm#44]
Thanks for a great and long awaited integration.
I seem to be missing the 4 temperature sensors for the air intake and outlet. Would it be possible to get those included - or have I just missed them somehow?

# temp sensors
      - name: Dantherm bryggers - Outdoor temperature
        unique_id: dantherm_bryggers_outdoor_temperature
        unit_of_measurement: °C
        device_class: temperature
        scan_interval: 5
        slave: 1
        address: 132
        #count: 2
        swap: word
        data_type: float32
        precision: 1
      - name: Dantherm bryggers - Supply temperature
        unique_id: dantherm_bryggers_supply_temperature
        unit_of_measurement: °C
        device_class: temperature
        scan_interval: 5
        slave: 1
        address: 134
        #count: 2
        swap: word
        data_type: float32
        precision: 1
      - name: Dantherm bryggers - Extract temperature
        unique_id: dantherm_bryggers_extract_temperature
        unit_of_measurement: °C
        device_class: temperature
        scan_interval: 5
        slave: 1
        address: 136
        #count: 2
        swap: word
        data_type: float32
        precision: 1
      - name: Dantherm bryggers - Exhaust temperature
        unique_id: dantherm_bryggers_exhaust_temperature
        unit_of_measurement: °C
        device_class: temperature
        scan_interval: 5
        slave: 1
        address: 138
        #count: 2
        swap: word
        data_type: float32
        precision: 1
        `

**Comment by Debug1Bug** [comment]
You are absolutely right, looking at it now, they are there. Sorry for the disturbance. Case closed.

**Comment by Debug1Bug** [comment]
User error.

**Comment by Tvalley71** [comment]
No problem
